server:
  port: 9090

# data source config
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:32770/camunda?createDatabaseIfNotExist=true
    username: root
    password: camunda123

management:
  endpoints:
    web:
      exposure:
        include: '*'

camunda.bpm:
  admin-user:
    id: kermit
    password: superSecret
    firstName: Kermit
  filter:
    create: All tasks
  database:
    type: mysql
logging:
  level:
    com.example: DEBUG
